
const Dates = {
    "characters": [
        {
            "id": 0,
            "name": "随机包",
            "img": "/images/0.jpg",
        },
        {
            "id": 1,
            "name": "豆沙包",
            "img": "/images/1.png",
        },
        {
            "id": 2,
            "name": "柠檬包",
            "img": "/images/2.png",
        },
        {
            "id": 3,
            "name": "蔬菜包",
            "img": "/images/3.png",
        },
        {
            "id": 4,
            "name": "海盐包",
            "img": "/images/4.png",
        },
        {
            "id": 5,
            "name": "眼影包",
            "img": "/images/5.png",
        },
        {
            "id": 6,
            "name": "可乐包",
            "img": "/images/6.png",
        },
        {
            "id": 7,
            "name": "非洲包",
            "img": "/images/7.png",
        },

    ],
    "player": {
        "character": null,
        "name": null,
        "money": null,
        "id": null,
    },
    "players": [
        {
            "character": {
                "id": 2,
                "name": "柠檬包",
                "img": "/images/2.png",
            },
            "name": "Joan",
            "money": 1000,
            "id": "Player1",
            "color": "white",
            "mapPosition": 1,
        },
        {
            "character": {
                "id": 4,
                "name": "海盐包",
                "img": "/images/4.png",
            },
            "name": "David",
            "money": 2000,
            "id": "Player2",
            "color": "white",
            "mapPosition": 30,
        },
    ],
    "map": {
        "cells": [
            //top
            {
                "id": 21,
                "height": 304,
                "width": 304,
                "top": 45,
                "left": 45,
            },
            {
                "id": 22,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 352,
            },
            {
                "id": 23,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 537,
            },
            {
                "id": 24,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 722,
            },
            {
                "id": 25,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 907,
            },
            {
                "id": 26,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 1092,
            },
            {
                "id": 27,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 1277,
            },
            {
                "id": 28,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 1462,
            },
            {
                "id": 29,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 1647,
            },
            {
                "id": 30,
                "height": 304,
                "width": 182,
                "top": 45,
                "left": 1832,
            },
            //right

            {
                "id": 31,
                "height": 304,
                "width": 304,
                "top": 45,
                "left": 2018,
            },
            {
                "id": 32,
                "height": 182,
                "width": 304,
                "top": 351,
                "left": 2018,
            },
            {
                "id": 33,
                "height": 182,
                "width": 304,
                "top": 536,
                "left": 2018,
            },
            {
                "id": 34,
                "height": 182,
                "width": 304,
                "top": 721,
                "left": 2018,
            },
            {
                "id": 35,
                "height": 182,
                "width": 304,
                "top": 906,
                "left": 2018,
            },
            {
                "id": 36,
                "height": 182,
                "width": 304,
                "top": 1091,
                "left": 2018,
            },
            {
                "id": 37,
                "height": 182,
                "width": 304,
                "top": 1276,
                "left": 2018,
            },
            {
                "id": 38,
                "height": 182,
                "width": 304,
                "top": 1461,
                "left": 2018,
            },
            {
                "id": 39,
                "height": 182,
                "width": 304,
                "top": 1646,
                "left": 2018,
            },
            {
                "id": 40,
                "height": 182,
                "width": 304,
                "top": 1831,
                "left": 2018,
            },
            //bottom

            {
                "id": 11,
                "height": 304,
                "width": 304,
                "top": 2017,
                "left": 45,
            },
            {
                "id": 10,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 352,
            },
            {
                "id": 9,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 537,
            },
            {
                "id": 8,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 722,
            },
            {
                "id": 7,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 907,
            },
            {
                "id": 6,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 1092,
            },
            {
                "id": 5,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 1277,
            },
            {
                "id": 4,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 1462,
            },
            {
                "id": 3,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 1647,
            },
            {
                "id": 2,
                "height": 304,
                "width": 182,
                "top": 2017,
                "left": 1832,
            },
            {
                "id": 1,
                "height": 304,
                "width": 304,
                "top": 2017,
                "left": 2018,
            },
            //left
            {
                "id": 20,
                "height": 182,
                "width": 304,
                "top": 351,
                "left": 45,
            },
            {
                "id": 19,
                "height": 182,
                "width": 304,
                "top": 536,
                "left": 45,
            },
            {
                "id": 18,
                "height": 182,
                "width": 304,
                "top": 721,
                "left": 45,
            },
            {
                "id": 17,
                "height": 182,
                "width": 304,
                "top": 906,
                "left": 45,
            },
            {
                "id": 16,
                "height": 182,
                "width": 304,
                "top": 1091,
                "left": 45,
            },
            {
                "id": 15,
                "height": 182,
                "width": 304,
                "top": 1276,
                "left": 45,
            },
            {
                "id": 14,
                "height": 182,
                "width": 304,
                "top": 1461,
                "left": 45,
            },
            {
                "id": 13,
                "height": 182,
                "width": 304,
                "top": 1646,
                "left": 45,
            },
            {
                "id": 12,
                "height": 182,
                "width": 304,
                "top": 1831,
                "left": 45,
            },
        ],
        "cards": [
            {
                "height": 312,
                "width": 455,
                "top": 550,
                "left": 474,
            },
            {
                "height": 312,
                "width": 455,
                "top": 1510,
                "left": 1428,
            }
        ]
    }
};

export default Dates;